# Generated by Django 3.2 on 2021-04-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210422_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='quantity',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.book'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stocks'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.author'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.city'),
        ),
    ]
